import { useState } from "react";
import { Alert, Button, Form, Input, Modal, Steps, Typography } from "antd";
import { LockOutlined, MailOutlined, SafetyCertificateOutlined } from "@ant-design/icons";
import axiosClient from "../../api/axiosClient";

export default function ForgotPasswordModal({ open, onClose, onSuccess }) {
    const [form] = Form.useForm(); const [step, setStep] = useState(0); const [email, setEmail] = useState(""); const [resetToken, setResetToken] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
    const close = () => { form.resetFields(); setStep(0); setEmail(""); setResetToken(""); setError(""); onClose(); };
    const submit = async (values) => { try { setLoading(true); setError(""); if (step === 0) { await axiosClient.post("/auth/forgot-password/request-otp", { email: values.email }); setEmail(values.email); setStep(1); } else if (step === 1) { const response = await axiosClient.post("/auth/forgot-password/verify-otp", { email, otp: values.otp }); setResetToken(response.data?.data?.resetToken); setStep(2); } else { await axiosClient.post("/auth/forgot-password/reset", { resetToken, newPassword: values.newPassword, confirmPassword: values.confirmPassword }); close(); onSuccess?.(); } } catch (requestError) { setError(requestError?.response?.data?.message || "We could not complete password recovery"); } finally { setLoading(false); } };
    return <Modal open={open} onCancel={close} footer={null} destroyOnClose width={460} title="Reset your password"><Steps size="small" current={step} items={[{ title: "Request" }, { title: "Verify" }, { title: "Reset" }]} style={{ marginBottom: 24 }} /><Typography.Paragraph type="secondary">{step === 0 ? "We will send a one-time code to your registered WhatsApp number." : step === 1 ? `Enter the 6-digit code sent to the WhatsApp number registered for ${email}.` : "Choose a new password for your account."}</Typography.Paragraph><Form form={form} layout="vertical" onFinish={submit} requiredMark={false}>{step === 0 && <Form.Item name="email" label="Email address" rules={[{ required: true, type: "email" }]}><Input prefix={<MailOutlined />} placeholder="name@company.com" /></Form.Item>}{step === 1 && <Form.Item name="otp" label="WhatsApp OTP" rules={[{ required: true }, { pattern: /^\d{6}$/, message: "Enter the 6-digit code" }]}><Input prefix={<SafetyCertificateOutlined />} inputMode="numeric" maxLength={6} placeholder="123456" /></Form.Item>}{step === 2 && <><Form.Item name="newPassword" label="New password" rules={[{ required: true, min: 8 }]}><Input.Password prefix={<LockOutlined />} /></Form.Item><Form.Item name="confirmPassword" label="Confirm password" dependencies={["newPassword"]} rules={[{ required: true }, ({ getFieldValue }) => ({ validator(_, value) { return !value || getFieldValue("newPassword") === value ? Promise.resolve() : Promise.reject(new Error("Passwords do not match")); } })]}><Input.Password prefix={<LockOutlined />} /></Form.Item></>}{error ? <Alert type="error" showIcon message={error} style={{ marginBottom: 16 }} /> : null}<Button type="primary" htmlType="submit" loading={loading} block>{step === 0 ? "Send WhatsApp code" : step === 1 ? "Verify code" : "Update password"}</Button></Form></Modal>;
}
